### ISSUE TITLE
Logger guidelines states that logging is enabled only for DEBUG builds

### ISSUE THREAD

**Issue by ataulm** [brightec/Guidelines_Android#1]
> Note that the Logger class will not log any message if in DEBUG build.

in https://github.com/brightec/Android_Guidelines/blob/master/project_and_code_guidelines.md

Does the Logger only log for release builds? Which logging mechanism is used for this?

**Comment by alistairsykes** [comment]
Thanks for spotting this. The sentence was just written incorrectly. See latest commit

> Note that the Logger class will only log messages if in a DEBUG build.

**Comment by ataulm** [comment]
:+1:
